spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.105/SpringCloud_Sell?CharacterEncoding=utf-8&useSSL=false
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 192.168.1.105
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081